import type { Metadata } from "next";
import { Geist, Geist_Mono, Prompt } from "next/font/google";
import "./globals.css";

const prompt= Prompt({
  subsets: ["thai","latin"],
  weight: ["100", "200", "300", "400", "500","600","700","800","900",],
});



export const metadata: Metadata = {
  title: "Food Tracker App",
  description: "Generated by Patcha",
  keywords: ["Food", "Tracker", "Health", "สุชภาพ", "อาหาร"],
  icons: {
    icon: "/vercel.svg",
  },
  authors: [{
    name: "Patcha",
    url: "https://patcha.dev",
  }]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${prompt.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
